import React from 'react';
import App from './App.jsx';

export default {
  title: 'AutoGenerated/App',
  component: App,
  parameters: {
    layout: 'fullscreen',
  },
};

export const Default = {};
