#!/usr/bin/env sh
. "${0%/*}/_/husky.sh"

export PATH="$PATH:/usr/local/bin:/usr/bin:~/.nvm/versions/node/$(node -v 2>/dev/null)/bin"

node scripts/verify-build.js
node scripts/generate-changelog.js
git add ARCHITECTURE.md CHANGELOG.md docs/LEGACY_BLUEPRINT.md docs/DECISIONS.md
